// Get Crypto List
GET https://api.cryptown-besquare.one/api/crypto/cryptoList 

###
// Get Crypto Detail
GET https://api.cryptown-besquare.one/api/crypto/cryptoDetail/bitcoin


###
GET https://api.cryptown-besquare.one/api/crypto/cryptoChartDaily/arpa


###
GET https://api.cryptown-besquare.one/api/crypto/cryptoChartWeekly/arpa


###
GET https://api.cryptown-besquare.one/api/crypto/cryptoChartMax/bitcoin


###

GET https://api.cryptown-besquare.one/api/crypto/cryptoTrending

###


