// Get Crypto List
GET https://api.cryptown-besquare.one/api/crypto/cryptoList 

###
// Get Crypto Detail
POST https://api.cryptown-besquare.one/api/crypto/cryptoDetail
content-type: application/json

{
    "cryptoId": "bitcoin"
}

###
POST https://api.cryptown-besquare.one/api/crypto/cryptoChartDaily
content-type: application/json

{
    "cryptoId": "arpa"
}

###
POST https://api.cryptown-besquare.one/api/crypto/cryptoChartWeekly
content-type: application/json

{
    "cryptoId": "arpa"
}

###
POST https://api.cryptown-besquare.one/api/crypto/cryptoChartMax
content-type: application/json

{
    "cryptoId": "bitcoin"
}

###

GET https://api.cryptown-besquare.one/api/crypto/cryptoTrending

###


