GET https://api.cryptown-besquare.one/api/post/getPosts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZGZkZjBhOC1jYjNlLTRkZWYtYWZhZS0zYzdhNDIyZjQyNzIiLCJpYXQiOjE2NjgzOTk3OTIsImV4cCI6MTY2ODQ4NjE5Mn0.CVK8gSCsm0yIHle9B8BUFU-IKM55BmeevHbaUQhS9T7vYyHgoerxd-lZ-JcrBJSXmJMZd6cmp6MKLL9hhCepGYL0roMFvDBgEYPHQGPee-4TOWlQU2x3kcPS5QylwIt3vdMGEPBH3Mvgb3G5fm0LnqMZZxGh5ZtQZ131NOAEcRoA1Bqq7af1gBje9kAQ4oI6_u3S5XC3a8ADEaQMaiD3TgxKfT9CUgsiYkcyC-oZoZXJY89A8Ip3n1YFFGicb8yITD_8LsVV48tieGIr1OLZyl89A4vh5YfYEb5RC80mRph9X2rrBGdon04rm4jwHDxbW6WO5obU95dPce8DO5Tq2A

###

POST https://api.cryptown-besquare.one/api/post/addPost
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZGZkZjBhOC1jYjNlLTRkZWYtYWZhZS0zYzdhNDIyZjQyNzIiLCJpYXQiOjE2NjgzOTk3OTIsImV4cCI6MTY2ODQ4NjE5Mn0.CVK8gSCsm0yIHle9B8BUFU-IKM55BmeevHbaUQhS9T7vYyHgoerxd-lZ-JcrBJSXmJMZd6cmp6MKLL9hhCepGYL0roMFvDBgEYPHQGPee-4TOWlQU2x3kcPS5QylwIt3vdMGEPBH3Mvgb3G5fm0LnqMZZxGh5ZtQZ131NOAEcRoA1Bqq7af1gBje9kAQ4oI6_u3S5XC3a8ADEaQMaiD3TgxKfT9CUgsiYkcyC-oZoZXJY89A8Ip3n1YFFGicb8yITD_8LsVV48tieGIr1OLZyl89A4vh5YfYEb5RC80mRph9X2rrBGdon04rm4jwHDxbW6WO5obU95dPce8DO5Tq2A
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMzlmNWZmYS1iMzkzLTQ2MzItYWZhNy0wMTdjZjBkYTZjNjgiLCJpYXQiOjE2Njc0NTQ5NzksImV4cCI6MTY2NzU0MTM3OX0.Id2dQQEW3DRQa6H60Nx3pGDZjMeYHEc5zJ3SFAyBIYk 
content-type: application/json

{
    "post": "THIS IS A TEST MAIN POST 1!!!",
    "dateTime": "2022-11-03T05:38:12.168Z"
}   

###
POST https://api.cryptown-besquare.one/api/post/addSubPost
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MTY4NjA5Ny0yODhiLTRkMjEtODBlYi04ZWEzNDY1M2ZhNDciLCJpYXQiOjE2Njc0NTM5MzMsImV4cCI6MTY2NzU0MDMzM30.N8YyWW_euXsRplxwjJIbDrYJHnr_787mviKN484snio
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZGZkZjBhOC1jYjNlLTRkZWYtYWZhZS0zYzdhNDIyZjQyNzIiLCJpYXQiOjE2NjgzOTk3OTIsImV4cCI6MTY2ODQ4NjE5Mn0.CVK8gSCsm0yIHle9B8BUFU-IKM55BmeevHbaUQhS9T7vYyHgoerxd-lZ-JcrBJSXmJMZd6cmp6MKLL9hhCepGYL0roMFvDBgEYPHQGPee-4TOWlQU2x3kcPS5QylwIt3vdMGEPBH3Mvgb3G5fm0LnqMZZxGh5ZtQZ131NOAEcRoA1Bqq7af1gBje9kAQ4oI6_u3S5XC3a8ADEaQMaiD3TgxKfT9CUgsiYkcyC-oZoZXJY89A8Ip3n1YFFGicb8yITD_8LsVV48tieGIr1OLZyl89A4vh5YfYEb5RC80mRph9X2rrBGdon04rm4jwHDxbW6WO5obU95dPce8DO5Tq2A
content-type: application/json

{
    "postId": "870b79fd-30ec-4b0c-a432-8cfe27cd056", 
    "post": "THIS IS A TEST SUB POST 1!!!",
    "dateTime": "2022-11-03T05:38:12.168Z"
}  
