##-------------Favourite-------------##
###
GET https://api.cryptown-besquare.one/api/favourite/favourite-list
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZTM1NWRiOS1mODEwLTQyMTMtYjUxZS1iMzBkZmYzMjFkNTkiLCJpYXQiOjE2Njg0OTA4MTgsImV4cCI6MTY2ODU3NzIxOH0.Foo5q9n5IEJgVgb1ae-8U-UfYOJ-W6_g512DpfJBjfkFND-WSBPFFaCxleQDFedccugLQ_sR4wbmskxfK2FphCyB_nUcNYuCmLz3YeRku-MdI-I3rvQ6D0zRhsk9Fw3m4AIKQOsWHYKlzVwm2KTkjI7xDbo_4xE9MOens7zLinBLMBiqWteEoHsUnwDDi3s0nffxprf0QOfcPNmuNhGHtrLbIz9SYlu8SmWtspHJM1_b3UdiG4y4iCdKEnxHsD0rZSNXVYIA9twtHBDLptyepjUVQF_otCbYualZyPy84ySPPI84GVdJWlYDH-AnMEh_KsC8L3dEZVcgZgX8Xp3YHg


###
POST https://api.cryptown-besquare.one/api/favourite/favourite-add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZjIwMWRiNy00NWE1LTQyNzAtOTJjYS0yNzFmOTk3ODM3M2IiLCJpYXQiOjE2Njc5NjY4NTUsImV4cCI6MTY2ODA1MzI1NX0.8RZuHxdlpKsdta8Nw39awsdaQaRnIcZfcJIagrk9lK4
content-type: application/json

{
    "cryptoId": "bitcoin-ID-4",
    "coinName": "bitcoin",
    "image_url": "<image URL>"
}

###
DELETE https://api.cryptown-besquare.one/api/favourite/favourite-delete
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZTM1NWRiOS1mODEwLTQyMTMtYjUxZS1iMzBkZmYzMjFkNTkiLCJpYXQiOjE2Njg0OTA4MTgsImV4cCI6MTY2ODU3NzIxOH0.Foo5q9n5IEJgVgb1ae-8U-UfYOJ-W6_g512DpfJBjfkFND-WSBPFFaCxleQDFedccugLQ_sR4wbmskxfK2FphCyB_nUcNYuCmLz3YeRku-MdI-I3rvQ6D0zRhsk9Fw3m4AIKQOsWHYKlzVwm2KTkjI7xDbo_4xE9MOens7zLinBLMBiqWteEoHsUnwDDi3s0nffxprf0QOfcPNmuNhGHtrLbIz9SYlu8SmWtspHJM1_b3UdiG4y4iCdKEnxHsD0rZSNXVYIA9twtHBDLptyepjUVQF_otCbYualZyPy84ySPPI84GVdJWlYDH-AnMEh_KsC8L3dEZVcgZgX8Xp3YHg
content-type: application/json

{
    "favId": "1065f052-b071-4c1d-9bd3-e2f246d93ecb"
}
