##-------------Favourite-------------##
###
GET http://localhost:5000/api/favourite/favourite-list
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNjEyZTE1My1hMTlkLTRjYTYtODcxOC1mY2UyMGRkYTA5MjIiLCJpYXQiOjE2NjczNTc2MTksImV4cCI6MTY2NzQ0NDAxOX0.Fb7Q71PkHayIQZl9zmIWMuXSK404oo-q22rkV8ZZEVw
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODE0NDQsImV4cCI6MTY2ODU2Nzg0NH0.O9NQEabp1ZM_yEYIuFWmhVbBTCqhjSY4gDVWuOkSNXe16-L0vd_p0XbH0vm6N5obE6wR0w3XflRr4oOB34ytsTa4egm2LQdNj6tHcg1yWeqbnQmF_WqbhjYJZe_otZRvMUaMliq5WGBWpeg1uq_WDr4C1FAzngD6dtoNb9pFHkSim0aR7we6GbHgWfpGKEoW96Zppsh_m-2JcyhJZJ5RYT9QaCEmy86pL7Q6cRWFOKL8ecOrGPl4kuv0daHfmH-MVww7whVTAwIzbWgdok8ZuZOB0_x6bhQUlaHFvn0uXs9jU147XKDvu6ctZqdMNNHtKpjFhuRoVGzHeNdWMtu_1A


###
POST http://localhost:5000/api/favourite/favourite-add
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNjEyZTE1My1hMTlkLTRjYTYtODcxOC1mY2UyMGRkYTA5MjIiLCJpYXQiOjE2NjczNTc2MTksImV4cCI6MTY2NzQ0NDAxOX0.Fb7Q71PkHayIQZl9zmIWMuXSK404oo-q22rkV8ZZEVw
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODE0NDQsImV4cCI6MTY2ODU2Nzg0NH0.O9NQEabp1ZM_yEYIuFWmhVbBTCqhjSY4gDVWuOkSNXe16-L0vd_p0XbH0vm6N5obE6wR0w3XflRr4oOB34ytsTa4egm2LQdNj6tHcg1yWeqbnQmF_WqbhjYJZe_otZRvMUaMliq5WGBWpeg1uq_WDr4C1FAzngD6dtoNb9pFHkSim0aR7we6GbHgWfpGKEoW96Zppsh_m-2JcyhJZJ5RYT9QaCEmy86pL7Q6cRWFOKL8ecOrGPl4kuv0daHfmH-MVww7whVTAwIzbWgdok8ZuZOB0_x6bhQUlaHFvn0uXs9jU147XKDvu6ctZqdMNNHtKpjFhuRoVGzHeNdWMtu_1A
content-type: application/json

{
    "cryptoId": "bitcoin-ID-2",
    "coinName": "bitcoin",
    "image": "<image URL>"
}

###
DELETE http://localhost:5000/api/favourite/favourite-delete
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNjEyZTE1My1hMTlkLTRjYTYtODcxOC1mY2UyMGRkYTA5MjIiLCJpYXQiOjE2NjczNTc2MTksImV4cCI6MTY2NzQ0NDAxOX0.Fb7Q71PkHayIQZl9zmIWMuXSK404oo-q22rkV8ZZEVw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzgzOWI2Yi1jNzFjLTQzYmEtYjg4NC0yZmIxZDBjZDk3YjgiLCJpYXQiOjE2Njc4Nzk2NDcsImV4cCI6MTY2Nzk2NjA0N30.1O19GC0zIDQ1G8PCTPvJgchdsWXreTLMfJT-PRzV1f8
content-type: application/json

{
    "favId": "d6ae6997-bbba-45a5-ba83-d9bd11b930eb"
}