// Get Crypto List
GET https://localhost:5000/api/crypto/cryptoList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM

###
// Get Crypto Detail
POST https://localhost:5000/api/crypto/cryptoDetail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM
content-type: application/json

{
    "cryptoId": "bitcoin"
}

###
POST https://localhost:5000/api/crypto/cryptoChartDaily
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM
content-type: application/json

{
    "cryptoId": "arpa"
}

###
POST https://localhost:5000/api/crypto/cryptoChartWeekly
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM
content-type: application/json

{
    "cryptoId": "arpa"
}

###
POST https://localhost:5000/api/crypto/cryptoChartMax
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM
content-type: application/json

{
    "cryptoId": "bitcoin"
}

###

GET https://localhost:5000/api/crypto/cryptoTrending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTM5MDc2NC0wMzM2LTQ4ZDEtYjk0MC01MTQ1MDU5MmI1ZTciLCJpYXQiOjE2NjcyMTA4MDUsImV4cCI6MTY2NzI5NzIwNX0.S-CA8VpJ-3-vL5BMAeSFukPHm31XOx1jXWOFsm68jOM

###


