##-------------Favourite-------------##
###
GET http://localhost:5000/api/favourite/favourite-list
# Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.ewogICJ1c2VySWQiOiAiZmVmZDY1NGItOWRiOC00ZDAwLWE3NzUtMmVmZjQzMzMyYzQ4IiwKICAiaWF0IjogMTY2ODQ4MTEyOCwKICAiZXhwIjogMTY2OTk2NzUyOAp9.
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg1NjczOTYsImV4cCI6MTY2ODY1Mzc5Nn0.MLevNmP12I8x-oDgZau28QKJDxeJuLJ-TlDbC6bD1WVLTGlN8S5wQXWtrq-huTQVC20t7W3wYT3u4p-L8O2ddKt6gAmQOIaqQoiCp1vInOl-hSKUZJvZUVvkpF82D-0LtuvkQQtOPrmtELyQ3Uyxe517aMeMQyQIVf7uim19MulMwfZXbyqhSYC2qrAHo17lIgbYidHiMROg5X0VWdPhUGG109sPjf2cidiSftG08U1go4Kw-QnAId2aGMBhAefh33MX8aLsxzNVmUyVMzoXyyLon-KP4KAiG4cTH1f77UW8ncddGTRqRh5AW6BwjgRlutsB4yjQPsal90HVS20AEg


###
POST http://localhost:5000/api/favourite/favourite-add
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMTk3Y2Y3MC1kNDViLTQwMDktOTBkNS1hNzY2MmY2MzhiNzgiLCJpYXQiOjE2Njg0ODE5NzgsImV4cCI6MTY2ODU2ODM3OH0.kMmaFaqeDVuTnPqWwS0i4ZYvxAxoHyBNiSUA_uxgjceO4DdYDaGEYGy3F9Mp2XMI0-odW1OTUyXIsMz5DzbvGVW5Qa_l3siUfpI7rpvULfu-ea62y1gUtgx7A1DtOSlvEBLMo4tjOVVOrukwpktZHTmUnNSM0BxhuTp0MeUOMAXFPAhpUClfXq9XOzPNTCCiBefeUCfS-A75ru3qYTLaTWN2TYZUp18KJubCQqatB2Ngg_02DLtxyNHLAULT1KAY2p_SYleFG8ev-VdzOTuKv9z-G8X3f35NDQDl5G3JvkImGwHYhXIoSesQrp7tES0940ZVv2fPTeTuuoW4_yhqdw
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODE0NDQsImV4cCI6MTY2ODU2Nzg0NH0.O9NQEabp1ZM_yEYIuFWmhVbBTCqhjSY4gDVWuOkSNXe16-L0vd_p0XbH0vm6N5obE6wR0w3XflRr4oOB34ytsTa4egm2LQdNj6tHcg1yWeqbnQmF_WqbhjYJZe_otZRvMUaMliq5WGBWpeg1uq_WDr4C1FAzngD6dtoNb9pFHkSim0aR7we6GbHgWfpGKEoW96Zppsh_m-2JcyhJZJ5RYT9QaCEmy86pL7Q6cRWFOKL8ecOrGPl4kuv0daHfmH-MVww7whVTAwIzbWgdok8ZuZOB0_x6bhQUlaHFvn0uXs9jU147XKDvu6ctZqdMNNHtKpjFhuRoVGzHeNdWMtu_1A
content-type: application/json

{
    "cryptoId": "bitcoin-ID-5",
    "coinName": "bitcoin",
    "image_url": "<image URL>"
}

###
DELETE http://localhost:5000/api/favourite/favourite-delete
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNjEyZTE1My1hMTlkLTRjYTYtODcxOC1mY2UyMGRkYTA5MjIiLCJpYXQiOjE2NjczNTc2MTksImV4cCI6MTY2NzQ0NDAxOX0.Fb7Q71PkHayIQZl9zmIWMuXSK404oo-q22rkV8ZZEVw
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMTk3Y2Y3MC1kNDViLTQwMDktOTBkNS1hNzY2MmY2MzhiNzgiLCJpYXQiOjE2Njg0ODE5NzgsImV4cCI6MTY2ODU2ODM3OH0.kMmaFaqeDVuTnPqWwS0i4ZYvxAxoHyBNiSUA_uxgjceO4DdYDaGEYGy3F9Mp2XMI0-odW1OTUyXIsMz5DzbvGVW5Qa_l3siUfpI7rpvULfu-ea62y1gUtgx7A1DtOSlvEBLMo4tjOVVOrukwpktZHTmUnNSM0BxhuTp0MeUOMAXFPAhpUClfXq9XOzPNTCCiBefeUCfS-A75ru3qYTLaTWN2TYZUp18KJubCQqatB2Ngg_02DLtxyNHLAULT1KAY2p_SYleFG8ev-VdzOTuKv9z-G8X3f35NDQDl5G3JvkImGwHYhXIoSesQrp7tES0940ZVv2fPTeTuuoW4_yhqdw
content-type: application/json

{
    "favId": "5707ef82-053d-4509-bb29-3ddda01a0372"
}