GET http://localhost:5000/api/post/getPosts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMTk3Y2Y3MC1kNDViLTQwMDktOTBkNS1hNzY2MmY2MzhiNzgiLCJpYXQiOjE2Njg3NTE2NTcsImV4cCI6MTY2ODgzODA1N30.qkLzAB9CmtZcbeyC4p__kHJ5-D5mQDZjjaBRHatFMNsl81oFEuIdFNLw4TBybO0NWt90TsepeLqbo5yzaaCtObMG7Fy2czo3Bq2-Dm_ajqCizSfVa1OpYAdJqVgaqLLxUXDZs9vWd1ONvmdcIGDACVjb_z4Zz4GFCUm0eDOXFD9EaM_g3o1la1RfGuipDmaO6PKAXUZV4yjhHuyLyeWwTfdMmegZPkPWgmVSCsTwZo7k8epApgbeYphcd53pUqZUQQcitM3rLVDYGup8IREzG5krAvGKBiUzDhulvCyVGmugoR8DiFlxkjIH3BfzN2NPGYvyRylrb-MpC5loC8_UYA



###

POST http://localhost:5000/api/post/addPost
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMTk3Y2Y3MC1kNDViLTQwMDktOTBkNS1hNzY2MmY2MzhiNzgiLCJpYXQiOjE2Njg3NTE2NTcsImV4cCI6MTY2ODgzODA1N30.qkLzAB9CmtZcbeyC4p__kHJ5-D5mQDZjjaBRHatFMNsl81oFEuIdFNLw4TBybO0NWt90TsepeLqbo5yzaaCtObMG7Fy2czo3Bq2-Dm_ajqCizSfVa1OpYAdJqVgaqLLxUXDZs9vWd1ONvmdcIGDACVjb_z4Zz4GFCUm0eDOXFD9EaM_g3o1la1RfGuipDmaO6PKAXUZV4yjhHuyLyeWwTfdMmegZPkPWgmVSCsTwZo7k8epApgbeYphcd53pUqZUQQcitM3rLVDYGup8IREzG5krAvGKBiUzDhulvCyVGmugoR8DiFlxkjIH3BfzN2NPGYvyRylrb-MpC5loC8_UYA
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMzlmNWZmYS1iMzkzLTQ2MzItYWZhNy0wMTdjZjBkYTZjNjgiLCJpYXQiOjE2Njc0NTQ5NzksImV4cCI6MTY2NzU0MTM3OX0.Id2dQQEW3DRQa6H60Nx3pGDZjMeYHEc5zJ3SFAyBIYk 
content-type: application/json

{
    "post": "This is the eight post from test2",
    "dateTime": "2022-11-18T05:32:22.329Z"
}   

###
POST http://localhost:5000/api/post/addSubPost
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MTY4NjA5Ny0yODhiLTRkMjEtODBlYi04ZWEzNDY1M2ZhNDciLCJpYXQiOjE2Njc0NTM5MzMsImV4cCI6MTY2NzU0MDMzM30.N8YyWW_euXsRplxwjJIbDrYJHnr_787mviKN484snio
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODExMjgsImV4cCI6MTY2ODU2NzUyOH0.wbN3UOIh6qpsh8QaWPsvXhADTuA3xVl2NTUzgD0GtvdFNwl6zwD7M7VHEj4tIFlYfWtkNsxkU0mX0QRKP_eChAoYmJca3dU3TtS_ehfJfgaGTdtc8YzQLeG3jWmI2GrBR3_ee7fh0M6SnWCDxTaNcVS-h9l9P2WA6F-9hnw1YaxZ6bNl2i-eclH52mvNwmd4-6qO7nksIHRXeLUwIjinW_4WxAS-oQS6gHEDHUnT8PbUnsUiyXnp1MyHLdPveQn_eO6ugoTEfQ2c5BhY_oDffb3xjzxlrQrMW8aYwRMxRidhC0n9VyrWXR0J6yky9SFmnbRSTKn63w8V3dGSkq6c0Q
content-type: application/json

{
    "postId": "b184ea78-a5a9-4b36-b3e0-6e8a81756ab4", 
    "post": "THIS IS A REVERSE SUB POST",
    "dateTime": "2022-11-03T05:38:12.168Z"
}  
