GET http://localhost:5000/api/post/getPosts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NDk3ZTQ5Zi1iYzZiLTQ0ZDYtYmRiOC1hNmNjMzUxZGEwN2IiLCJpYXQiOjE2Njg3NTg5OTIsImV4cCI6MTY2ODg0NTM5Mn0.bQSg0TK1qTSfSoWEWwQTjAIWjAZEK_Yl5vj9kGzG5Flt2M9SaPZ4SlsP2LDfLDkf432zB3xpQAhjqcWcLaxfFHNpbNifYyBzxJKniKo92C1nNjHqUEEl9syUU_gxpCOwwm5MiMJFWoJyPzd2zMP_EG17RQPykp3HRLARVKNn_szKv6CxeZTKbtyYW9dSNobXiEmm-Z8rky1KX7CTxMmHO-H_eMKIiNjPw0y8d_x4ZH69yhRRVFnQFN1Eu43FVrHIFa3YURBsizx0RLU-Su0y4YPV_2hRaKFV6Snz7UJsREZFpWj2bjjh5-hhuiUQN_g_01HZrMdRtGW_6GUxSC8_ig
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZjc0OWMxMy02ZWMwLTQzMWYtYWViMC0xYThjYzgzMmY3ZGYiLCJpYXQiOjE2Njg3NTkxODUsImV4cCI6MTY2ODg0NTU4NX0.XNTg_DVrRcUQRne13Tgbq3hwNR8uGyWrJFrmgNCpGeraqnE0yfuzS_zAzK5Ml05aIxi1P3GMZy23i_sZ2gF3F5JjUdpp6YAGrmHhwmXNVGL3vGzEoKHBU2HCHmiV3bdtt5pqSojTUePjcxadjjPcFVxsvTr8iP8swq_Rlxq463m8a0OJdZjELKVBS7O61njTGEuEgKZGvf5rV3BT1WZWtszlwX4iz16ukDk0Fq-a93_0JoUGLMoaQHJT4tTMRvBuSP0x1Ldp_xbnZfJ-TSWvVXGYf_ZuNWfB54yExv3WxhVcf7pyLgBe3PJix3IzkjEjTvaQn_4Bg_PCruiQwLwXkA


###

POST http://localhost:5000/api/post/addPost
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NDk3ZTQ5Zi1iYzZiLTQ0ZDYtYmRiOC1hNmNjMzUxZGEwN2IiLCJpYXQiOjE2Njg3NTg5OTIsImV4cCI6MTY2ODg0NTM5Mn0.bQSg0TK1qTSfSoWEWwQTjAIWjAZEK_Yl5vj9kGzG5Flt2M9SaPZ4SlsP2LDfLDkf432zB3xpQAhjqcWcLaxfFHNpbNifYyBzxJKniKo92C1nNjHqUEEl9syUU_gxpCOwwm5MiMJFWoJyPzd2zMP_EG17RQPykp3HRLARVKNn_szKv6CxeZTKbtyYW9dSNobXiEmm-Z8rky1KX7CTxMmHO-H_eMKIiNjPw0y8d_x4ZH69yhRRVFnQFN1Eu43FVrHIFa3YURBsizx0RLU-Su0y4YPV_2hRaKFV6Snz7UJsREZFpWj2bjjh5-hhuiUQN_g_01HZrMdRtGW_6GUxSC8_ig
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZjc0OWMxMy02ZWMwLTQzMWYtYWViMC0xYThjYzgzMmY3ZGYiLCJpYXQiOjE2Njg3NTkxODUsImV4cCI6MTY2ODg0NTU4NX0.XNTg_DVrRcUQRne13Tgbq3hwNR8uGyWrJFrmgNCpGeraqnE0yfuzS_zAzK5Ml05aIxi1P3GMZy23i_sZ2gF3F5JjUdpp6YAGrmHhwmXNVGL3vGzEoKHBU2HCHmiV3bdtt5pqSojTUePjcxadjjPcFVxsvTr8iP8swq_Rlxq463m8a0OJdZjELKVBS7O61njTGEuEgKZGvf5rV3BT1WZWtszlwX4iz16ukDk0Fq-a93_0JoUGLMoaQHJT4tTMRvBuSP0x1Ldp_xbnZfJ-TSWvVXGYf_ZuNWfB54yExv3WxhVcf7pyLgBe3PJix3IzkjEjTvaQn_4Bg_PCruiQwLwXkA 
content-type: application/json

{
    "post": "Main Post 2 test2",
    "dateTime": "2022-11-18T05:32:22.329Z"
}   

###
POST http://localhost:5000/api/post/addSubPost
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NDk3ZTQ5Zi1iYzZiLTQ0ZDYtYmRiOC1hNmNjMzUxZGEwN2IiLCJpYXQiOjE2Njg3NTg5OTIsImV4cCI6MTY2ODg0NTM5Mn0.bQSg0TK1qTSfSoWEWwQTjAIWjAZEK_Yl5vj9kGzG5Flt2M9SaPZ4SlsP2LDfLDkf432zB3xpQAhjqcWcLaxfFHNpbNifYyBzxJKniKo92C1nNjHqUEEl9syUU_gxpCOwwm5MiMJFWoJyPzd2zMP_EG17RQPykp3HRLARVKNn_szKv6CxeZTKbtyYW9dSNobXiEmm-Z8rky1KX7CTxMmHO-H_eMKIiNjPw0y8d_x4ZH69yhRRVFnQFN1Eu43FVrHIFa3YURBsizx0RLU-Su0y4YPV_2hRaKFV6Snz7UJsREZFpWj2bjjh5-hhuiUQN_g_01HZrMdRtGW_6GUxSC8_ig
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZjc0OWMxMy02ZWMwLTQzMWYtYWViMC0xYThjYzgzMmY3ZGYiLCJpYXQiOjE2Njg3NTkxODUsImV4cCI6MTY2ODg0NTU4NX0.XNTg_DVrRcUQRne13Tgbq3hwNR8uGyWrJFrmgNCpGeraqnE0yfuzS_zAzK5Ml05aIxi1P3GMZy23i_sZ2gF3F5JjUdpp6YAGrmHhwmXNVGL3vGzEoKHBU2HCHmiV3bdtt5pqSojTUePjcxadjjPcFVxsvTr8iP8swq_Rlxq463m8a0OJdZjELKVBS7O61njTGEuEgKZGvf5rV3BT1WZWtszlwX4iz16ukDk0Fq-a93_0JoUGLMoaQHJT4tTMRvBuSP0x1Ldp_xbnZfJ-TSWvVXGYf_ZuNWfB54yExv3WxhVcf7pyLgBe3PJix3IzkjEjTvaQn_4Bg_PCruiQwLwXkA
content-type: application/json

{
    "postId": "37056c87-4eb7-42e4-8cde-1ddf0c6e1060", 
    "post": "Sub Post 1 from test1 Main post 1",
    "dateTime": "2022-11-03T05:38:12.168Z"
}  

###
GET http://localhost:5000/api/post/getUserPosts
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NDk3ZTQ5Zi1iYzZiLTQ0ZDYtYmRiOC1hNmNjMzUxZGEwN2IiLCJpYXQiOjE2Njg3NTg5OTIsImV4cCI6MTY2ODg0NTM5Mn0.bQSg0TK1qTSfSoWEWwQTjAIWjAZEK_Yl5vj9kGzG5Flt2M9SaPZ4SlsP2LDfLDkf432zB3xpQAhjqcWcLaxfFHNpbNifYyBzxJKniKo92C1nNjHqUEEl9syUU_gxpCOwwm5MiMJFWoJyPzd2zMP_EG17RQPykp3HRLARVKNn_szKv6CxeZTKbtyYW9dSNobXiEmm-Z8rky1KX7CTxMmHO-H_eMKIiNjPw0y8d_x4ZH69yhRRVFnQFN1Eu43FVrHIFa3YURBsizx0RLU-Su0y4YPV_2hRaKFV6Snz7UJsREZFpWj2bjjh5-hhuiUQN_g_01HZrMdRtGW_6GUxSC8_ig
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZjc0OWMxMy02ZWMwLTQzMWYtYWViMC0xYThjYzgzMmY3ZGYiLCJpYXQiOjE2Njg3NTkxODUsImV4cCI6MTY2ODg0NTU4NX0.XNTg_DVrRcUQRne13Tgbq3hwNR8uGyWrJFrmgNCpGeraqnE0yfuzS_zAzK5Ml05aIxi1P3GMZy23i_sZ2gF3F5JjUdpp6YAGrmHhwmXNVGL3vGzEoKHBU2HCHmiV3bdtt5pqSojTUePjcxadjjPcFVxsvTr8iP8swq_Rlxq463m8a0OJdZjELKVBS7O61njTGEuEgKZGvf5rV3BT1WZWtszlwX4iz16ukDk0Fq-a93_0JoUGLMoaQHJT4tTMRvBuSP0x1Ldp_xbnZfJ-TSWvVXGYf_ZuNWfB54yExv3WxhVcf7pyLgBe3PJix3IzkjEjTvaQn_4Bg_PCruiQwLwXkA
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMDFkOWZmZS1lODJiLTQ4NzktYjNmNi0yZGYyZjVmZTRhMzQiLCJpYXQiOjE2Njg3NjIwNzMsImV4cCI6MTY2ODg0ODQ3M30.TpmnppbOP__njjIJlMKFHNwLHl4YiFr5RO2kBTryLqKbaFYv29Jl53VJ7ko0yElizXEIZ-3jMOUdxA7x0ETEvmO1r1uwSEGeRK1l7vAMe_CPA9E-M2-4BxvutAPArXXZT9MYI8oZZAYtBxgGC9E5iy4RmkdV8V0r4VlWJPPOXTDIx8HHt6c-Ju-rGOckAwDfZ4zZQSZp6CakLefTp9pkCewKNCOQh8BtadzUWU9Bcx5N4nT1Azgsq6iIcLfw7VHVH3h2R05xQ_oMke_5Csz3VExXn9i31DbQ8m8c2ml5CMcDJa9NbUhDw4LzXE6LCxd5nQItOxoA1miKwXe8B0zjGQ

###
DELETE http://localhost:5000/api/post/post-delete
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NDk3ZTQ5Zi1iYzZiLTQ0ZDYtYmRiOC1hNmNjMzUxZGEwN2IiLCJpYXQiOjE2Njg3NTg5OTIsImV4cCI6MTY2ODg0NTM5Mn0.bQSg0TK1qTSfSoWEWwQTjAIWjAZEK_Yl5vj9kGzG5Flt2M9SaPZ4SlsP2LDfLDkf432zB3xpQAhjqcWcLaxfFHNpbNifYyBzxJKniKo92C1nNjHqUEEl9syUU_gxpCOwwm5MiMJFWoJyPzd2zMP_EG17RQPykp3HRLARVKNn_szKv6CxeZTKbtyYW9dSNobXiEmm-Z8rky1KX7CTxMmHO-H_eMKIiNjPw0y8d_x4ZH69yhRRVFnQFN1Eu43FVrHIFa3YURBsizx0RLU-Su0y4YPV_2hRaKFV6Snz7UJsREZFpWj2bjjh5-hhuiUQN_g_01HZrMdRtGW_6GUxSC8_ig
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZjc0OWMxMy02ZWMwLTQzMWYtYWViMC0xYThjYzgzMmY3ZGYiLCJpYXQiOjE2Njg3NTkxODUsImV4cCI6MTY2ODg0NTU4NX0.XNTg_DVrRcUQRne13Tgbq3hwNR8uGyWrJFrmgNCpGeraqnE0yfuzS_zAzK5Ml05aIxi1P3GMZy23i_sZ2gF3F5JjUdpp6YAGrmHhwmXNVGL3vGzEoKHBU2HCHmiV3bdtt5pqSojTUePjcxadjjPcFVxsvTr8iP8swq_Rlxq463m8a0OJdZjELKVBS7O61njTGEuEgKZGvf5rV3BT1WZWtszlwX4iz16ukDk0Fq-a93_0JoUGLMoaQHJT4tTMRvBuSP0x1Ldp_xbnZfJ-TSWvVXGYf_ZuNWfB54yExv3WxhVcf7pyLgBe3PJix3IzkjEjTvaQn_4Bg_PCruiQwLwXkA
content-type: application/json

{
    "postId": "37056c87-4eb7-42e4-8cde-1ddf0c6e1060"
}