GET http://localhost:5000/api/post/getPosts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg1NzExOTUsImV4cCI6MTY2ODY1NzU5NX0.NuNbcQ05kP9ynTzQ_L0BU_olM6-4kHzzkNquUqfVwUA1tj56W1D_4HfDo7lQ_B9yOGJg5BmFJGfDv7wCc51LYt3uVO36XXQEoJHQCFFEisLWNSdHvjJd1Uqxa6C2dprTLwJz1_TqH42dDPtZGXHECgkPNTERz2aAuKEjIf6PfiOEK5AxySFJK4VQqZngo6oGp-sgEpKqpEGKtUdwjp_xl213n-ZZ8XPELR5jAZZvXaU1S0L02sfTBMK9GRJeTea7WEbct9ZJdg2PhSoKvQS8--yRIEu1Eq5Q92PnZ4HMMbGU83ENgsGYlWUklDZ4PccOrqWMjIRGPOxWnvnCJRa1bg


###

POST http://localhost:5000/api/post/addPost
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODExMjgsImV4cCI6MTY2ODU2NzUyOH0.wbN3UOIh6qpsh8QaWPsvXhADTuA3xVl2NTUzgD0GtvdFNwl6zwD7M7VHEj4tIFlYfWtkNsxkU0mX0QRKP_eChAoYmJca3dU3TtS_ehfJfgaGTdtc8YzQLeG3jWmI2GrBR3_ee7fh0M6SnWCDxTaNcVS-h9l9P2WA6F-9hnw1YaxZ6bNl2i-eclH52mvNwmd4-6qO7nksIHRXeLUwIjinW_4WxAS-oQS6gHEDHUnT8PbUnsUiyXnp1MyHLdPveQn_eO6ugoTEfQ2c5BhY_oDffb3xjzxlrQrMW8aYwRMxRidhC0n9VyrWXR0J6yky9SFmnbRSTKn63w8V3dGSkq6c0Q
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMzlmNWZmYS1iMzkzLTQ2MzItYWZhNy0wMTdjZjBkYTZjNjgiLCJpYXQiOjE2Njc0NTQ5NzksImV4cCI6MTY2NzU0MTM3OX0.Id2dQQEW3DRQa6H60Nx3pGDZjMeYHEc5zJ3SFAyBIYk 
content-type: application/json

{
    "post": "THIS IS A TEST MAIN POST 2!!!",
    "dateTime": "2022-11-03T05:38:12.168Z"
}   

###
POST http://localhost:5000/api/post/addSubPost
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MTY4NjA5Ny0yODhiLTRkMjEtODBlYi04ZWEzNDY1M2ZhNDciLCJpYXQiOjE2Njc0NTM5MzMsImV4cCI6MTY2NzU0MDMzM30.N8YyWW_euXsRplxwjJIbDrYJHnr_787mviKN484snio
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODExMjgsImV4cCI6MTY2ODU2NzUyOH0.wbN3UOIh6qpsh8QaWPsvXhADTuA3xVl2NTUzgD0GtvdFNwl6zwD7M7VHEj4tIFlYfWtkNsxkU0mX0QRKP_eChAoYmJca3dU3TtS_ehfJfgaGTdtc8YzQLeG3jWmI2GrBR3_ee7fh0M6SnWCDxTaNcVS-h9l9P2WA6F-9hnw1YaxZ6bNl2i-eclH52mvNwmd4-6qO7nksIHRXeLUwIjinW_4WxAS-oQS6gHEDHUnT8PbUnsUiyXnp1MyHLdPveQn_eO6ugoTEfQ2c5BhY_oDffb3xjzxlrQrMW8aYwRMxRidhC0n9VyrWXR0J6yky9SFmnbRSTKn63w8V3dGSkq6c0Q
content-type: application/json

{
    "postId": "28484f0f-3b24-4927-a424-f738e18e3c5e", 
    "post": "THIS IS A TEST SUB POST 2!!!",
    "dateTime": "2022-11-03T05:38:12.168Z"
}  
