
##-------------Login/Register-------------##
POST http://localhost:5000/api/user/login
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "Password@12345"
}

###
POST http://localhost:5000/api/user/signup
content-type: application/json

{
    "email": "test2@gmail.com",
    "username": "test2",
    "password": "Password@12345",
    "confirm_password": "Password@12345"
}

##-------------Profile/Update-------------##
###
GET http://localhost:5000/api/user/profile
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODExMjgsImV4cCI6MTY2ODU2NzUyOH0.wbN3UOIh6qpsh8QaWPsvXhADTuA3xVl2NTUzgD0GtvdFNwl6zwD7M7VHEj4tIFlYfWtkNsxkU0mX0QRKP_eChAoYmJca3dU3TtS_ehfJfgaGTdtc8YzQLeG3jWmI2GrBR3_ee7fh0M6SnWCDxTaNcVS-h9l9P2WA6F-9hnw1YaxZ6bNl2i-eclH52mvNwmd4-6qO7nksIHRXeLUwIjinW_4WxAS-oQS6gHEDHUnT8PbUnsUiyXnp1MyHLdPveQn_eO6ugoTEfQ2c5BhY_oDffb3xjzxlrQrMW8aYwRMxRidhC0n9VyrWXR0J6yky9SFmnbRSTKn63w8V3dGSkq6c0Q

###

PATCH http://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZWZkNjU0Yi05ZGI4LTRkMDAtYTc3NS0yZWZmNDMzMzJjNDgiLCJpYXQiOjE2Njg0ODExMjgsImV4cCI6MTY2ODU2NzUyOH0.wbN3UOIh6qpsh8QaWPsvXhADTuA3xVl2NTUzgD0GtvdFNwl6zwD7M7VHEj4tIFlYfWtkNsxkU0mX0QRKP_eChAoYmJca3dU3TtS_ehfJfgaGTdtc8YzQLeG3jWmI2GrBR3_ee7fh0M6SnWCDxTaNcVS-h9l9P2WA6F-9hnw1YaxZ6bNl2i-eclH52mvNwmd4-6qO7nksIHRXeLUwIjinW_4WxAS-oQS6gHEDHUnT8PbUnsUiyXnp1MyHLdPveQn_eO6ugoTEfQ2c5BhY_oDffb3xjzxlrQrMW8aYwRMxRidhC0n9VyrWXR0J6yky9SFmnbRSTKn63w8V3dGSkq6c0Q
content-type: application/json

{
    "username": "Test1",
    "password": "Password@12345",
    "confirm_password": "Password@12345"
}
