
##-------------Login/Register-------------##
POST https://localhost:5000/api/user/login
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "Password@12345"
}

###
POST https://localhost:5000/api/user/signup
content-type: application/json

{
    "email": "test1@gmail.com",
    "username": "test1",
    "password": "Password@12345",
    "confirm_password": "Password@12345"
}

##-------------Profile/Update-------------##
###
GET https://localhost:5000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzgzOWI2Yi1jNzFjLTQzYmEtYjg4NC0yZmIxZDBjZDk3YjgiLCJpYXQiOjE2Njc1NDY2MDgsImV4cCI6MTY2NzYzMzAwOH0.BpeSaOYLhl8fKVBnbdyKBcfHoPIdjHUyBq0_Xl-YgGQ


###

PATCH https://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNzgzOWI2Yi1jNzFjLTQzYmEtYjg4NC0yZmIxZDBjZDk3YjgiLCJpYXQiOjE2Njc1NDY2MDgsImV4cCI6MTY2NzYzMzAwOH0.BpeSaOYLhl8fKVBnbdyKBcfHoPIdjHUyBq0_Xl-YgGQ
content-type: application/json

{
    "username": "Test1",
    "password": "Password@12345",
    "confirm_password": "Password@12345"
}
